ALTER TABLE empresas
ADD COLUMN IF NOT EXISTS nit VARCHAR(30);

ALTER TABLE empresas
ADD COLUMN IF NOT EXISTS razon_social VARCHAR(180);

ALTER TABLE empresas
ADD COLUMN IF NOT EXISTS direccion TEXT;

ALTER TABLE empresas
ADD COLUMN IF NOT EXISTS codigo_establecimiento VARCHAR(20);

ALTER TABLE empresas
ADD COLUMN IF NOT EXISTS afiliacion_iva VARCHAR(40);

ALTER TABLE empresas
ADD COLUMN IF NOT EXISTS correo VARCHAR(120);
