ALTER TABLE productos
ADD COLUMN IF NOT EXISTS tipo_producto VARCHAR(40) DEFAULT 'producto',
ADD COLUMN IF NOT EXISTS se_fabrica BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS numero_serie VARCHAR(120),
ADD COLUMN IF NOT EXISTS medida_compra VARCHAR(40),
ADD COLUMN IF NOT EXISTS equivalente_inventario NUMERIC(12,4) DEFAULT 1,
ADD COLUMN IF NOT EXISTS medida_inventario VARCHAR(40),
ADD COLUMN IF NOT EXISTS departamento VARCHAR(120),
ADD COLUMN IF NOT EXISTS subcategoria VARCHAR(120),
ADD COLUMN IF NOT EXISTS familia VARCHAR(120),
ADD COLUMN IF NOT EXISTS cuenta_contable VARCHAR(120),
ADD COLUMN IF NOT EXISTS centro_costo VARCHAR(120);
